name: demo2
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - expat=2.7.3=h9214b88_0
  - glib=2.84.4=h60240c0_0
  - glib-tools=2.84.4=h3823947_0
  - gst-plugins-base=1.24.11=h3fe0a9e_0
  - gstreamer=1.24.11=h233a61a_0
  - icu=75.1=he0c23c2_0
  - krb5=1.21.3=hdf4eb48_0
  - libclang13=21.1.7=default_ha2db4b5_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libogg=1.3.5=h2466b09_1
  - libpng=1.6.53=h7351971_0
  - libsqlite=3.51.1=hf5d6505_0
  - libvorbis=1.3.7=h5112557_2
  - libxml2=2.13.9=h741aa76_0
  - libxslt=1.1.43=h25c3957_0
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.46=h3402e2f_0
  - pip=25.3=pyhc872135_0
  - ply=3.11=pyhd8ed1ab_3
  - python=3.11.14=h981015d_0
  - python_abi=3.11=2_cp311
  - qt-main=5.15.15=hb098fff_5
  - setuptools=80.9.0=py311haa95532_0
  - sip=6.10.0=py311h3e6a449_1
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - accelerate==1.12.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - attrs==25.4.0
      - bidict==0.23.1
      - blinker==1.9.0
      - boto3==1.42.11
      - botocore==1.42.11
      - brotli==1.2.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - chattts==0.2.4
      - click==8.3.1
      - colorama==0.4.6
      - comtypes==1.4.14
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cryptography==46.0.3
      - cycler==0.12.1
      - dashscope==1.25.2
      - datasets==3.2.0
      - dill==0.3.7
      - edge-tts==7.2.7
      - einops==0.8.1
      - einx==0.3.0
      - encodec==0.1.1
      - fastapi==0.123.5
      - filelock==3.20.0
      - flask==3.1.2
      - flask-cors==6.0.1
      - flask-login==0.6.3
      - flask-socketio==5.5.1
      - fonttools==4.61.1
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2023.6.0
      - ftfy==6.3.1
      - funcy==2.0
      - gevent==25.9.1
      - geventhttpclient==2.3.5
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - iniconfig==2.3.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - locust==2.42.6
      - locust-cloud==1.29.5
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - modelscope==1.33.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.15
      - networkx==3.6
      - numba==0.63.1
      - numpy==1.26.4
      - open-clip-torch==3.2.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - orjson==3.11.5
      - pandas==2.3.3
      - peft==0.18.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - pyarrow>=15.0.0,<18.0.0
      - pyaudio==0.2.14
      - pybase16384==0.3.8
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygame==2.6.1
      - pygments==2.19.2
      - pymilvus==2.6.5
      - pyparsing==3.2.5
      - pypiwin32==223
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.2
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-engineio==4.12.3
      - python-socketio==5.15.0
      - pyttsx3==2.99
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2025.11.3
      - requests==2.32.4
      - s3transfer==0.16.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - simple-websocket==1.1.0
      - simsimd==6.5.3
      - six==1.17.0
      - sounddevice==0.5.3
      - srt==3.5.3
      - starlette==0.50.0
      - stringzilla==4.5.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - timm==1.0.22
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - trl==0.25.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - ultralytics==8.3.237
      - ultralytics-thop==2.0.18
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - vector-quantize-pytorch==1.27.14
      - vocos==0.1.0
      - vosk==0.3.45
      - wcwidth==0.2.14
      - weaviate==0.1.2
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.4
      - whisper==1.1.10
      - wsproto==1.3.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zope-event==6.1
      - zope-interface==8.1.1
prefix: D:\worksoft\anconda\anconda\envs\demo1
